### ISSUE TITLE
Can you provide the code for CAM and SAM to generate the pseudo labels?

### ISSUE THREAD

**Issue by XZNWU** [cskyl/SAM_WSSS#1]
Thank you very much for providing the code. Can you provide the code for CAM and SAM to generate the pseudo labels?

**Comment by cskyl** [comment]
Sure, thank you for the suggestion, we will try to include the code in our repo.

For now, the code for generate the pseudo-labels is adapted from [Transcam ](https://github.com/liruiwen/TransCAM), and the one for generated SAM's masks is borrowed from the official [SAM repo](https://github.com/facebookresearch/segment-anything). 
Hope this is helpful.
