### ISSUE TITLE
The code for SAM

### ISSUE THREAD

**Issue by lzl2040** [cskyl/SAM_WSSS#6]
I do not find the code for SAM. Where is the code?

**Comment by cskyl** [comment]
The code for SAM is available at https://github.com/facebookresearch/segment-anything. (The official repo)
Please let me know if you have any issues when running it.

**Comment by cskyl** [comment]
> I do not find the code for SAM. Where is the code?
The code for SAM is available at https://github.com/facebookresearch/segment-anything. (The official repo)
Please let me know if you have any issues when running it.
