### ISSUE TITLE
Why are you using black and white pseudo label where as in paper, it is mentioned as colored ?

### ISSUE THREAD

**Issue by ravi2kavi** [cskyl/SAM_WSSS#8]

**Comment by cskyl** [comment]
Hi, thank you for your question.
If you mean the visualization of the masks generated by SAM, as SAM doesn't provide any semantic information (no classes info), we use black and white visualization to show only the boundary of the masks. We suppose this can illustrate the message more clear. 
Thank you and please let me know if you have other comments!
